### ISSUE TITLE
Protection signs not working

### ISSUE THREAD

**Issue by cloakfox** [CryptoMorin/KingdomsX#1]
![2020-11-27_14 23 45](https://user-images.githubusercontent.com/3696645/100453994-4d12e180-30bc-11eb-9d37-178b17bbbd86.png)

Tried all different sign types

Paper 1.16.4
Kingdoms-1.10.6.0.0.1

**Comment by CryptoMorin** [comment]
https://github.com/CryptoMorin/KingdomsX/blob/1748055f542d3a3fa90b23031d1a04ec50291888/src/main/resources/protection-signs.yml#L66

I'm assuming yours looks like `signs: ['*']` which is from the old config and no longer works.

**Comment by cloakfox** [comment]
Fixed thanks!
