### ISSUE TITLE
Polish translation - lots of mistakes

### ISSUE THREAD

**Issue by Ksewedo5** [CryptoMorin/KingdomsX#10]
The Polish translation is really terrible, it contains a lot of errors ... and it looks like it was translated by a google translator

**Comment by CryptoMorin** [comment]
I've informed the person who translated the plugin, but keep in mind that all translations are community based and I'm not responsible if the person doesn't do anything about it.

**Comment by Ksewedo5** [comment]
https://github.com/CryptoMorin/KingdomsX/blob/f977a6cbfaca280dce49fc7c88ec30dfb6861661/src/main/resources/languages/pl.yml#L108 
https://github.com/CryptoMorin/KingdomsX/blob/f977a6cbfaca280dce49fc7c88ec30dfb6861661/src/main/resources/languages/pl.yml#L110
https://github.com/CryptoMorin/KingdomsX/blob/f977a6cbfaca280dce49fc7c88ec30dfb6861661/src/main/resources/languages/pl.yml#L112 !!!!!!!!!!!! 
https://github.com/CryptoMorin/KingdomsX/blob/f977a6cbfaca280dce49fc7c88ec30dfb6861661/src/main/resources/languages/pl.yml#L114
https://github.com/CryptoMorin/KingdomsX/blob/f977a6cbfaca280dce49fc7c88ec30dfb6861661/src/main/resources/languages/pl.yml#L175 ???
https://github.com/CryptoMorin/KingdomsX/blob/f977a6cbfaca280dce49fc7c88ec30dfb6861661/src/main/resources/languages/pl.yml#L294 ??? Według mnie powinno być ,,Do wieżyczki" 
https://github.com/CryptoMorin/KingdomsX/blob/f977a6cbfaca280dce49fc7c88ec30dfb6861661/src/main/resources/languages/pl.yml#L361
https://github.com/CryptoMorin/KingdomsX/blob/f977a6cbfaca280dce49fc7c88ec30dfb6861661/src/main/resources/languages/pl.yml#L706 ? :) 

PL: To są jedynie przykłady, gdyby przeczytać spolszczenie od początku do końca... myślę że, znalazłbym więcej błędów.
ENG: These are just examples, if I read the translate from start to finish ... I think I would find more bugs.

PL: Spolszczenie jest słabej jakości, należy trochę przy nim popracować żeby było naprawdę czytelne i zrozumiałe. Rozumiem że spolszczenie jest robione przez społeczność i autor pluginu nie odpowiada za jego stan :)))
ENG: The translate is of poor quality, you should work with it a bit to make it really legible and understandable. I understand that the translate is made by the community and the author of the plug is not responsible for its condition :)))

**Comment by resteqs** [comment]
Dobry wieczór, tłumaczyłem ten plugin od 250 linijki na język polski. Co do 1-4 to nie moje błędy, ale już je poprawiłem 5 literówka dzięki! 6. Jak dla mnie obie wersje są językowo poprawne, ale do brzmi jednak lepiej 7. kicknięty nie jest błędem w slangu internetowym tak jak wygooglować 8. you cant transfer nothing - Nie można transferować niczego. You cant transfer anything - Nie możesz niczego transferować. W pluginie użyto 1 wersji. Proszę cię o dalszy kontakt na dc resteqs#0534. Chciałem jeszcze zaznaczyć, że jest to 50 stron A4 i tłumaczyłem ten plik codziennie od 22-1, każdemu mogą zdarzyć się błędy przy tak dużej robocie. Warto zaznaczyć jeszcze, że publikacja tłumaczenia jest jedynie moją dobrą wolą i nic nie stoi na przeszkodzie poprawienia tych błędów samemu! Jeśli nie potrafisz pobrać locales z pliku jar mogę ci go wysłać. Jeśli uważasz, że moja praca jest słabej jakości, to zachęcam cię do zrobienia własnego tłumaczenia i wysłania go developerowi. Do tłumaczenia nie użyto google translate.
Miłego dnia

P.S *myślę, że *Popracować, żeby *Rozumiem, że   Uważaj na interpunkcję :)))

**Comment by Ksewedo5** [comment]
Masz rację, jest naprawdę dużo rzeczy to przetłumaczenia... powinienem łagodniej zwrócić na to uwagę ;) Co do pracy nad spolszczeniem... moglibyśmy się kontaktować na discordzie lub wstawiać zmiany bezpośrednio tutaj. Trzymaj się ciepło :D

**Comment by resteqs** [comment]
Nie ma problemu! Przyznam, że trochę się wkurzyłem haha. Czekam na kontakt!

**Comment by CryptoMorin** [comment]
I'm guessing this is taken care of in #12, so I'm closing this.
