### ISSUE TITLE
function auto-update does not work

### ISSUE THREAD

**Issue by Ksewedo5** [CryptoMorin/KingdomsX#16]
The new plugin version is being downloaded. The server does not replace files automatically ///Plugin.yml? ///
platform: Windows 10, other plugins update without problems

Server tree -> 
![github3](https://user-images.githubusercontent.com/54962940/105708715-1ec34e00-5f15-11eb-81f3-39fc7d01e542.png)

bukkit.yml ->
![github2](https://user-images.githubusercontent.com/54962940/105708773-2edb2d80-5f15-11eb-97b7-1e7072867057.png)

Kingdoms config ->
![github1](https://user-images.githubusercontent.com/54962940/105708803-37336880-5f15-11eb-860f-50c306ee8e01.png)
Console -> 
![github4](https://user-images.githubusercontent.com/54962940/105708894-516d4680-5f15-11eb-81d9-c7353cf56972.png)

After restarting the server, the message that the new version has been downloaded appears again.

**Comment by CryptoMorin** [comment]
Read the `path` option carefully.
