### ISSUE TITLE
why the defense tower in this plug-in attacks friendly NPCs in the ancient war 2mod

### ISSUE THREAD

**Issue by zhibeigg** [CryptoMorin/KingdomsX#18]
我想问一下，这个插件中的防御塔为什么会攻击古代战争2mod中的友方npc，如何让防御塔不攻击友方npc和生物？还有插件的防御塔有事会不攻击敌方npc和刷新的怪物，只有我重新放置防御塔或者手动放置怪让防御塔攻击后所有防御塔才能刷新回正常攻击状态。怎么解决这两个问题？
I want to ask why the defense tower in this plug-in attacks friendly NPCs in the ancient war 2mod, and how to make the defense tower not attack friendly NPCs and creatures? There are also plug-in defense towers that do not attack enemy NPCs and refreshed monsters. Only when I reposition the defense tower or manually place monsters to make the defense tower attack, can all defense towers refresh back to the normal attack state. How to solve these two problems?

**Comment by CryptoMorin** [comment]
I've already said this in the discord server. Mods and plugins are not compatible.
