### ISSUE TITLE
Bossbar broken?

### ISSUE THREAD

**Issue by Stormez1998** [CryptoMorin/KingdomsX#19]
Hay,

i can´t join the discord so i open here a ticket.

On my server i have activated Plunder. But at the bossbar is showing chapionshealt i removed the placeholder for Championhealt but it stays there. Screenshot follow:
![2022-01-04_05 23 33](https://user-images.githubusercontent.com/57358176/148009489-1c9dcd51-e82d-4dfa-bdce-3c92d8c8346e.png)

is that a bug? bcs i want only to show the plunder bossbar. The config should be finde:
![Screenshot 2022-01-04 052907](https://user-images.githubusercontent.com/57358176/148009702-96330cf7-5d5e-4910-a8b0-f2c4cab889ae.png)
![Screenshot 2022-01-04 052940](https://user-images.githubusercontent.com/57358176/148009703-d87be62e-4f8d-4d91-9635-e12d456117c8.png)

Best wishes Stormez

**Comment by CryptoMorin** [comment]
You have to copy the same title from `defender-bossbar` to [here](https://github.com/CryptoMorin/KingdomsX/blob/b698ec37d84303657285e873cf0c44dd9d8035a1/src/main/resources/invasions.yml#L161)

**Comment by Stormez1998** [comment]
It says the save. i replaced the title fom defender bossbar to line 161 but it still say the same.

invading.yml : https://pastebin.com/x2rXVtxK

**Comment by CryptoMorin** [comment]
You just entirely commented the option out.

**Comment by Stormez1998** [comment]
fk. Thanks xD i was not realize that
