### ISSUE TITLE
Nations randomly getting deleted

### ISSUE THREAD

**Issue by cloakfox** [CryptoMorin/KingdomsX#2]
Getting reports from our players that their nations are randomly getting deleted.

Currently running version 1.10.6.0.1
on paper 1.16.4

Startup logs shows this
`[02:03:01] [Server thread/INFO]: [Foxcraft] Invalid nation data for Scarface (9cd63437-8f89-4aa1-91db-f153061a8796) kingdom. Removing data...`

`[02:23:49] [Server thread/INFO]: [Foxcraft] Invalid nation data for InfoBroker (442e4994-f38c-4a18-a2c5-62a1fb7fd576) kingdom. Removing data...`

This is quite a severe issue.

**Comment by CryptoMorin** [comment]
Related to #4

**Comment by CryptoMorin** [comment]
The tax issues should be fixed in v1.10.7, but it's possible that the data might start detecting corruptions again.
If that happened, please give me all your 3 data folders (Players, Kingdoms, Lands) from the last time that the plugin ran successfully on a version that didn't have this issue.
