### ISSUE TITLE
Too many open Files

### ISSUE THREAD

**Issue by Stormez1998** [CryptoMorin/KingdomsX#20]
Hello, me again :D 

After some time on the Server my Cosnole get Spammed form KingdomsX. It say "Too many open Files". After that happend, the root server starts to struggle and cant even keep the Webserver up. So i have to stop the server but then theres is a delay till it works. While that happen its not possible to use ingame commands like /k home.

how can i fix that?

**Comment by CryptoMorin** [comment]
You need to contact your hosting provider with the full logs. This is usually a misconfiguration on their server.

**Comment by Stormez1998** [comment]
Im running on Linux Debian 10, do u know the commands to increase the ammount?

**Comment by CryptoMorin** [comment]
You can just Google around. Here's [one](https://www.tecmint.com/increase-set-open-file-limits-in-linux/) I found which seems to have the complete info for both hard/soft limits.

**Comment by Stormez1998** [comment]
I have already also seen that but i was not sure how much i have to set, that this will not happen again. Have u a hint for me how much i could set?

**Comment by Stormez1998** [comment]
So i have set my files up to 6553 before it was 1024, i maked it all like in the video was said. And it Changed (see Screenshot)
But after 5 min launching the Server the same Error happend again...
![Screenshot 2022-01-09 075559](https://user-images.githubusercontent.com/57358176/148672428-781ab55e-4613-4046-a4d4-dbd271b2502d.png)

Btw i launching my Servers via Pufferpanel. But i gave also the main root and the pufferpaneluser this ammount of files. (Also see in the screen above. Is that eventually a Problem with the Panel?

**Comment by CryptoMorin** [comment]
Can you `cat /etc/security/limits.conf`?

**Comment by Stormez1998** [comment]
Sure, Thanks for ur help.

`# /etc/security/limits.conf
#
#Each line describes a limit for a user in the form:
#
#<domain>        <type>  <item>  <value>
#
#Where:
#<domain> can be:
#        - a user name
#        - a group name, with @group syntax
#        - the wildcard *, for default entry
#        - the wildcard %, can be also used with %group syntax,
#                 for maxlogin limit
#        - NOTE: group and wildcard limits are not applied to root.
#          To apply a limit to the root user, <domain> must be
#          the literal username root.
#
#<type> can have the two values:
#        - "soft" for enforcing the soft limits
#        - "hard" for enforcing hard limits
#
#<item> can be one of the following:
#        - core - limits the core file size (KB)
#        - data - max data size (KB)
#        - fsize - maximum filesize (KB)
#        - memlock - max locked-in-memory address space (KB)
#        - nofile - max number of open file descriptors
#        - rss - max resident set size (KB)
#        - stack - max stack size (KB)
#        - cpu - max CPU time (MIN)
#        - nproc - max number of processes
#        - as - address space limit (KB)
#        - maxlogins - max number of logins for this user
#        - maxsyslogins - max number of logins on the system
#        - priority - the priority to run user process with
#        - locks - max number of file locks the user can hold
#        - sigpending - max number of pending signals
#        - msgqueue - max memory used by POSIX message queues (bytes)
#        - nice - max nice priority allowed to raise to values: [-20, 19]
#        - rtprio - max realtime priority
#        - chroot - change root to directory (Debian-specific)
#
#<domain>      <type>  <item>         <value>
#

#*               soft    core            0
#root            hard    core            100000
#*               hard    rss             10000
#@student        hard    nproc           20
#@faculty        soft    nproc           20
#@faculty        hard    nproc           50
#ftp             hard    nproc           0
#ftp             -       chroot          /ftp
#@student        -       maxlogins       4
#*               soft    nofile          4096
#*               soft    nofile          8192

# End of file

root  soft  nofile  65535
root  hard  nofile  65535
`

when i do ulimit -a = `core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 515374
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65535
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 515374
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
`

**Comment by CryptoMorin** [comment]
It should inherit the limit, but add `pufferpanel - nofile 65535` (assuming pufferpanel is the user that the panel uses) just in case.
If that didn't work, I guess puffer panel does have its own config. You might want to try asking them if there's a config for that.

**Comment by Stormez1998** [comment]
i will ask them :) 
will write you back here if i know more.

**Comment by Stormez1998** [comment]
Playceholder API is the reasson why this error happens. I use the Placholders from KingdomsX in a scoreboard and now me and an  other dev figure out that this happens only when PlaceholderAPI is installed

**Comment by CryptoMorin** [comment]
Yes, this happens because somewhere in a plugin you're using top kingdom placeholders and papi is requesting kingdoms to queue top kingdoms. Since top kingdoms require all kingdoms data to be loaded (which doesn't happen normally) that happens.  But not PlaceholderAPI is not the primary reason, it's the top placeholders. Even without papi, if you used those placeholders, that could still happen.

**Comment by Stormez1998** [comment]
Yes it was the Top list in the Scooreboard.
