### ISSUE TITLE
Member and allies are shown as placeholders in /k show

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [CryptoMorin/KingdomsX#22]
Server version: `git-Paper-408 (MC: 1.17.1)`
Plugin version: `Kingdoms-1.12.5.jar`

Description:
Using `/k show` displays the `%members%` and `%allies%` instead of players/kingdoms.

Steps to reproduce:
1. Install KingdomsX
2. Create a Kingdom
3. Use /k show

Image:
![k-show](https://user-images.githubusercontent.com/16565567/156927274-f7abaf71-e2c6-4f9d-b9fa-5d498e400ae2.png)

**Comment by CryptoMorin** [comment]
Replace all `COMPLEX:` with `@` in your language config.
