### ISSUE TITLE
Warp Pads display placeholder instead of name

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [CryptoMorin/KingdomsX#24]
Server version: `git-Paper-408 (MC: 1.17.1)`
Plugin version: `Kingdoms-1.12.5.jar`

Description:
Instead of displaying the warp pad name it shows `%warppad%`.

Steps to reproduce:
1. Install KingdomsX
2. Create a Kingdom
3. Buy some Warp Pads
4. Setup Warp Pads with custom names
5. Try to warp
6. See "%warppad% [world], [x], [y], [z]"

Image:
![warp-pads](https://user-images.githubusercontent.com/16565567/156927532-b0d5ac9c-de61-4722-9f33-4653f3eb21fa.png)

**Comment by CryptoMorin** [comment]
Replace it with `%structure-name%`
