### ISSUE TITLE
Permissions can't be turned off

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [CryptoMorin/KingdomsX#25]
Server version: `git-Paper-408 (MC: 1.17.1)`
Plugin version: `Kingdoms-1.12.5.1.jar`

Description:
Leaders can't turn off permissions in their kingdom's ranks. Clicking on a permission does nothing and it stays green.

Steps to reproduce:

1. Install KingdomsX.
2. Create a Kingdom.
3. Go into the rank permissions in the Nexus.
4. Try changing a permission to off and nothing happens.

Image:
![k-nexus-ranks](https://user-images.githubusercontent.com/16565567/156934143-07ef42f2-7265-458c-be00-e9af46e856f2.png)

**Comment by CryptoMorin** [comment]
Delete `rank-editor.yml` in [nexus GUI folder](https://github.com/CryptoMorin/KingdomsX/tree/master/src/main/resources/guis/en/structures/nexus)
