### ISSUE TITLE
Nexus Members bug

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [CryptoMorin/KingdomsX#26]
Plugin version: ` Kingdoms version 1.12.5.1.1.2`

Every member in a Kingdom is renamed to the king's name and shows their info as the king's.
Highlighted member in the attached image is a member of the Kingdom and not the king.

![nexus-members](https://user-images.githubusercontent.com/16565567/157654203-0652abe5-6b6d-490a-ae7a-9f29f405b36d.png)

**Comment by CryptoMorin** [comment]
Fixed in v1.12.6
