### ISSUE TITLE
missing config option

### ISSUE THREAD

**Issue by cloakfox** [CryptoMorin/KingdomsX#3]
`[02:02:25] [Server thread/WARN]: [Kingdoms] Missing config option tax.kingdoms.members.age. Using the default value.`

Is missing from the config, and will not generate in a fresh config either (tested this obviously)

Currently running version 1.10.6.0.1
on paper 1.16.4

**Comment by cloakfox** [comment]
Edit this seems to have been fixed in latest dev build, not sure why it's not mentioned in change logs

**Comment by CryptoMorin** [comment]
Yes, I sometimes forget to include minor changes like this in the changelog since no one reported it.
