### ISSUE TITLE
Compatible with GriefPrevention

### ISSUE THREAD

**Issue by WongIong** [CryptoMorin/KingdomsX#30]
GriefPrevention supports many plugins that KingdomsX does. So i think we may can utilize that to create more great experience.
Such as: some plugins will not modify GriefPrevention's region.

**Comment by CryptoMorin** [comment]
What's the suggestion here exactly? How can I utilize the fact that "two plugins support the same set of plugins"?
Generally you can't have two land management plugins working together. Are you asking to prevent people from claiming chunks that is protected by GriefPrevention?

**Comment by WongIong** [comment]
I dont know if it is possible, it just a thinking.
So if we could create a same region with GriefPrevention when KingdomsX does, we may can have more plugins to support KingdomsX and we don't need to compatible with all of them. Because they will respect to the region from GriefPrevention.
In this case the GriefPrevention region should have no control flags.

**Comment by CryptoMorin** [comment]
You can't have both GriefPrevention and kingdoms in the same chunk if that's what you're asking.

**Comment by WongIong** [comment]
okay, then seems it is not possible
