### ISSUE TITLE
Can't right click blocks

### ISSUE THREAD

**Issue by Jacqueb-1337** [CryptoMorin/KingdomsX#32]
Players can't click on doors, chests, barrels, brewing stands, and even the nexus itself while holding any item. Players have to use an empty hand to click any block.

Edit: I was wrong about the bug so I changed my description

**Comment by CryptoMorin** [comment]
1. Does this happen when holding specific items? 
2. Does this happen to certain places in the world? 
3. Does this happen to specific players? 
4. Do you get a message when you can't right-click?
5. Can you right-click any structures or turrets?
6. What plugin and server version are you using?
7. Is there any error in your console?

**Comment by Jacqueb-1337** [comment]
1. No, any item as far as I can tell.
2. I believe it's in claimed land
3. Everyone
4. No message at all
5. Not sure, haven't gotten that far
6. Latest plugin, spigot 1.18.2
7. No

**Comment by CryptoMorin** [comment]
I wanted to say this could also be a plugin conflict, but if it **only** happens in claimed lands and **everyone** is having this issue then I really have no clue.
