### ISSUE TITLE
"Back Button" in Resource Points Converter gui dupe

### ISSUE THREAD

**Issue by SathlerMC** [CryptoMorin/KingdomsX#33]
**Server Software :** Paper
**Minecraft Server :** 1.18.2
**Plugins :** Kingdoms-1.13.9

Put items in the Resource Points Converter gui and click the Back Button, items will be duped

**Video Link :** https://drive.google.com/file/d/1LAamWtKRr3muoTiJReCh-GkPbVWdU99V/view?usp=sharing

**Comment by CryptoMorin** [comment]
As you can see, I'm unable to reproduce it:
![Animation](https://user-images.githubusercontent.com/25098093/177024373-253bc42e-8354-49a1-9abb-92647822b727.gif)

I'm not sure what could be causing it, but you can start with removing all your other plugins, and then temporarily resetting all your configs to see which one's the issue.
