### ISSUE TITLE
KingdomsX does not function properly on 1.12.2

### ISSUE THREAD

**Issue by 1233Ao** [CryptoMorin/KingdomsX#34]
**If the player enters the game, the server reports an error in the background：**
![QQ截图20220716231558](https://user-images.githubusercontent.com/100471776/179360974-ce911cc4-6e6c-42c4-8973-f64b3059e24e.jpg)
**If the player sends a message, the server background reports an error, and the message cannot be sent：**
![QQ截图20220716231537](https://user-images.githubusercontent.com/100471776/179360980-477583db-6a24-4934-87be-0766d5ca1d62.jpg)
**If the player exits the server, the server reports an error in the background：**
![QQ截图20220716231611](https://user-images.githubusercontent.com/100471776/179361062-c25d05d1-4e65-40b3-a882-8e8ebbe0a2b5.jpg)
I use Microsoft Translator, so there may be some syntax errors
The server side is paper-1.12.2-1620

**Comment by CryptoMorin** [comment]
You're not using the latest version of the plugin. Please update.
