### ISSUE TITLE
Feature request: allow players to reapawn at their bed or respwan anchor instead of kingdom home.

### ISSUE THREAD

**Issue by Cloak3** [CryptoMorin/KingdomsX#36]
When the respawn-at-kingdom-home option is set to "true", players seem no longer able to set their respawn points with beds or respawn anchors. Could there be an option to prioritize players' custom respawn points over their kingdom home?

**Comment by CryptoMorin** [comment]
Sure of course

**Comment by CryptoMorin** [comment]
Added in v1.14.4.1-BETA
