### ISSUE TITLE
I would like to have the language file packaged in ZIP for us to download

### ISSUE THREAD

**Issue by BaiJiu123** [CryptoMorin/KingdomsX#44]
I am a server owner from China , For some unknown reason, I did not succeed in downloading the Chinese language pack , I also do not know how to download the corresponding language package in the Github file library of KingdomsX , So I would really like the language package to be individually packaged in ZIP and made available for us users to download, thanks

**Comment by CryptoMorin** [comment]
Hi, it's explained how to manually install language packs [here](https://github.com/CryptoMorin/KingdomsX/wiki/FAQ#network-issues-with-language-packs--addons).
