### ISSUE TITLE
Plugin Jobs and Kingdoms cause spam on the actionbar

### ISSUE THREAD

**Issue by Ksewedo5** [CryptoMorin/KingdomsX#47]
When the player is employed as an "Explorer" when the message about earned money appears, after a moment a message from kingdoms appears about entering unoccupied territory

https://youtu.be/fUvePrR3zAA

**Comment by CryptoMorin** [comment]
So what seems to be strange here?

**Comment by Ksewedo5** [comment]
Normally, this message appears when I leave the kingdom area. The player traverses the map (e.g. 1000 blocks) and 3 seconds +- receives information that he is in an unoccupied area. By default, the player is in an unoccupied area, should he get a message only when he enters a kingdom?. See my video on youtube how it looks like

**Comment by CryptoMorin** [comment]
If you're not using v1.15.4 you should update to the latest version, that should fix your issue.

**Comment by Ksewedo5** [comment]
The bug is present on version 1.15.4

**Comment by CryptoMorin** [comment]
Then I don't think I understood your report.

> By default, the player is in an unoccupied area, should he get a message only when he enters a kingdom

This is not technically true. The player will get a message when they enter a different "type" of land. Types of lands include wilderness, claimed and nation zones. And these types have different types itself like allies, truces, etc. So technically speaking a player will still receive a message when they go to an unclaimed land from a claimed land.
