### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to Kingdoms v1.10.6.2

### ISSUE THREAD

**Issue by cloakfox** [CryptoMorin/KingdomsX#5]
https://pastebin.com/Cg2aBHwF

Using Paper 1.16.4

**Comment by CryptoMorin** [comment]
This has been fixed in v1.10.7
It seems to be a very rare issue that can only happen exactly when the invasion has ended. I made some changes, this should fix it. If it happened again, please let me know in this issue.
