### ISSUE TITLE
LuckPerms not found

### ISSUE THREAD

**Issue by Ksewedo5** [CryptoMorin/KingdomsX#55]
![Screenshot_5](https://github.com/CryptoMorin/KingdomsX/assets/54962940/71b521f9-6f9f-4a12-97d1-588b7ec0a556)

![Screenshot_6](https://github.com/CryptoMorin/KingdomsX/assets/54962940/ddb7d177-3378-4881-8948-ba4e4dc2f79f)

![Screenshot_7](https://github.com/CryptoMorin/KingdomsX/assets/54962940/16ef3a55-39c0-4ec0-9e21-a02d00757477)

**Comment by CryptoMorin** [comment]
Can you try removing all plugins except Kingdoms and LuckPerms to see if it works that way?

**Comment by Ksewedo5** [comment]
I can't do that because it will cause a lot of errors (map generator etc). 


I ran tests. The message says luckperms was not found... but the integration is working fine.

Context:
HasKingdom - Work 
territory - (Only tested ,,Self" and ,,Enemy") - Work 
It's just that the message displayed at startup is not true

**Comment by CryptoMorin** [comment]
Unfortunately I can't reproduce it and I don't know why it'd be happening to you. The only thing I can think of is if this still happens to you if you remove all other plugins, but you said you can't do that.
![image](https://github.com/CryptoMorin/KingdomsX/assets/25098093/5c3f38cb-2a11-4df5-a3f3-a3ae740005d0)
