### ISSUE TITLE
healing turret does not working.

### ISSUE THREAD

**Issue by ben7147** [CryptoMorin/KingdomsX#57]
healing turret does not working.

**Comment by AfkF24** [comment]
Please provide more information, support can’t be provide through a GitHub issue. 

* What’s your server version?
* What’s your Kingdoms version?
* Does the turret have ammo?
* Are you in admin mode (`/k admin bypass`)?
* Did you try whether the turret works on a server without any other plugins?

**Comment by ben7147** [comment]
server version: 1.20
kingdoms version: latest
yes, the turret is full with ammo (6000ammo)
I am not in admin mode
no, but the flame turret works fine.

**Comment by ben7147** [comment]
I have a suggestion: in pacifist mode the healing turret does not work... please fix it

**Comment by AfkF24** [comment]
> I have a suggestion: in pacifist mode the healing turret does not work... please fix it

Will forward this to Discord so it's easier to keep track of

**Comment by ben7147** [comment]
ok

**Comment by AfkF24** [comment]
Closing this in favor of the Discord bug report, thanks
