### ISSUE TITLE
Ability to hide markers such as the nexus for bluemap/alternative in the config

### ISSUE THREAD

**Issue by waylenwasywas** [CryptoMorin/KingdomsX#58]
When looking at the bluemap (unsure if issue is with dynmap) the markers for the kingdoms nexus, "home" and the national spawn all show up and are generally all clumped together, making the map look messy/disorganized from a larger zoom area. On my server, I don't want the national spawn or the "home" marker displayed due to a lack of relevancy within the server. I was wondering if I could already disable/edit the displayed markers and if not, future plans to add this to the functionality. 

Cheers
<img width="1362" alt="image" src="https://github.com/CryptoMorin/KingdomsX/assets/35209231/5ede3b30-5f15-416b-a98a-e66c6b4ff5b4">
<img width="1362" alt="image" src="https://github.com/CryptoMorin/KingdomsX/assets/35209231/b151275f-6b27-4add-9cc3-0149808d4a63">
<img width="1362" alt="image" src="https://github.com/CryptoMorin/KingdomsX/assets/35209231/58981bb3-1fd7-44e0-b361-43536aded7fb">

**Comment by CryptoMorin** [comment]
You can disable them inside `plugins/Kingdoms/maps/map.yml` under `icons` section either set the global `enabled` option to false or add that option to the icons you don't want individually.
