### ISSUE TITLE
Cant change chat color per group

### ISSUE THREAD

**Issue by bsolyom** [CryptoMorin/KingdomsX#59]
Hello, I can't format the chat color in config.yml in groupColor.
I tried to add the groups I created in luckperms with perm_color_groupname, but the color of all chat messages is the same.
How can I change it from group to group?
The console says luckperms hooked.

**Comment by CryptoMorin** [comment]
> Hello, I can't format the chat color in config.yml in groupColor. I tried to add the groups I created in luckperms with perm_color_groupname, but the color of all chat messages is the same. How can I change it from group to group? The console says luckperms hooked.

Hi, it's going to be much easier for me to help you if you give me your LuckPerms group data, config.yml and chat.yml files.

**Comment by bsolyom** [comment]
Hi, the chat.yml (as txt):
[chat.txt](https://github.com/CryptoMorin/KingdomsX/files/12334740/chat.txt)
config.yml:
[config.txt](https://github.com/CryptoMorin/KingdomsX/files/12334749/config.txt)
The developer group in luckperms:
![image](https://github.com/CryptoMorin/KingdomsX/assets/63775925/cb914131-de6d-4986-9e78-04399b846814)

**Comment by CryptoMorin** [comment]
The problem is that you commented out the option in config.yml. So it's not even recognized:
```yml
    groupColor:
      #perm_color_developer: '&f'
#    ^ Hashtag means a comment
      #else: '&f'
```

So:

```yml
    groupColor:
      perm_color_developer: '&f'
      else: '&f'
```

And fyi, the developer group needs to have the `color.developer` permission, but since you gave it `*` it should work too.

**Comment by bsolyom** [comment]
I removed the #, but it didn't work, but the problem was that the owner also had * permission, and the chat color was therefore the same for him as for the developer, but I fixed it by setting the owner's color.developer permission to false, thank you.
