### ISSUE TITLE
[Suggestion] Support MiniMessage

### ISSUE THREAD

**Issue by TheFloodDragon** [CryptoMorin/KingdomsX#64]
**MiniMessage** is a modern and easily used library for text-message handling from [adventure](https://github.com/KyoriPowered/adventure).

It's widely used in many plugins, even the server core of [Paper](https://docs.papermc.io/paper/dev/component-api/introduction#minimessage).

So I'd like to use MiniMessage in [KingdomsX](https://github.com/CryptoMorin/KingdomsX) with gradient and more features, I really want it.

Hoping for the result, although it won't be easy to support this, thanks!

**Comment by CryptoMorin** [comment]
I'm sorry but the plugin already has it's own system. If you're looking for gradient colors specifically, it's planned for the upcoming version.
