### ISSUE TITLE
KingdomsX support 

### ISSUE THREAD

**Issue by merto06** [CryptoMorin/KingdomsX#69]
I want to condition the KingdomsX plugin's upgrades using CMI ranks, for example, but when I try to do it like shown in the image, it doesn't appear in the game
![adadwawdawd](https://github.com/user-attachments/assets/13d60398-e335-4bde-80dc-2eccadc6da9f)

**Comment by CryptoMorin** [comment]
Wasn't this already answered in the Discord server?
