### ISSUE TITLE
Players can't access the settings in the nexus

### ISSUE THREAD

**Issue by cloakfox** [CryptoMorin/KingdomsX#8]
Paper 1.16.4

These issues that appear every version are getting annoying. I've already expressed my feelings about how things are currently being done. It's disappointing that none of it is taken serious.

https://pastebin.com/KXSXqzMY

I can't wait for the day this goes open source.

**Comment by CryptoMorin** [comment]
Related to #6 

> It's disappointing that none of it is taken serious.

I'm not sure what you mean by not "serious" Some of these bugs aren't as simple as just creating a kingdom and playing around for 5mins. They're reproduced with an active playerbase that changed various default settings. It's surely understandable that I don't have the time to test every single possible thing in the plugin before releasing the version.
