### ISSUE TITLE
HeadDisplays suddenly having hard time because of Kingdoms

### ISSUE THREAD

**Issue by cloakfox** [CryptoMorin/KingdomsX#9]
(happening since latest version)

https://pastebin.com/jfKMFxs0

![Capture](https://user-images.githubusercontent.com/3696645/101239642-7ac5df00-36e9-11eb-8f50-f47c242db4a9.PNG)
This guys kingdom is also bugged randomly (possibly related to error above)

https://pastebin.com/qxmDqJ4d

**Comment by cloakfox** [comment]
A lot of ccommands also broke:
/k top
/k home
/k invade
/k info

**Comment by CryptoMorin** [comment]
Fixed in v1.10.8.2
